name: Preview Deployment

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'docs/**'
      - mkdocs.yml

jobs:
  deploy-to-cloud-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Deploy app
        uses: superfly/flyctl-actions/setup-flyctl@master
        env: 
         FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
      - name: Post PR comment with preview deployment URL
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |  
            Successfully deployed preview revision at https://pr-${{github.event.number}}---myapp-abcdef123-ab.a.run.app
          allow-repeats: false